INSERT INTO NFLTeam (NFL_Team, Coach_LastName, Coach_FirstName)
VALUES
('Dallas Cowboys','McCarthy','Mike'),
('Washington Football Team','Rivera','Ron'),
('Philadelphia Eagles','Sirianni','Nick'),
('New York Giants','Judge','Joe'),
('Atlanta Falcons','Smith','Arthur'),
('New Orleans Saints','Payton','Sean'),
('Carolina Panthers','Rhule','Matt'),
('Tampa Bay Buccaneers','Arians','Bruce'),
('Los Angeles Rams','McVay','Sean'),
('San Francisco 49ers','Shanahan','Kyle'),
('Seattle Seahawks','Carroll','Pete'),
('Arizona Cardinals','Kingsbury','Kliff'),
('Green Bay Packers','LaFleur','Matt'),
('Chicago Bears','Nagy','Matt'),
('Minnesota Vikings','Zimmer','Mike'),
('Detroit Lions','Campbell','Dan'),
('New England Patriots','Belichick','Bill'),
('Miami Dolphins','Flores','Brian'),
('Buffalo Bills','McDermott','Sean'),
('New York Jets','Saleh','Robert'),
('Indianapolis Colts','Reich','Frank'),
('Jacksonville Jaguars','Meyer','Urban'),
('Houston Texans','Gulley','David'),
('Tennessee Titans','Vrabel','Mike'),
('Los Angeles Chargers','Staley','Brandon'),
('Las Vegas Raiders','Gruden','Jon'),
('Kansas City Chiefs','Reid','Andy'),
('Denver Broncos','Fangio','Vic'),
('Baltimore Ravens','Harbaugh','John'),
('Pittsburgh Steelers','Tomlin','Mike'),
('Cincinnati Bengals','Taylor','Zac'),
('Cleveland Browns','Stefanski','Kevin')